import type { ShDegree, SplatStore } from '../model/SplatStore';
import { shCoefficients } from '../model/SplatStore';
import { SH_C0 } from './plyReader';

type ExportStore = Pick<
  SplatStore,
  | 'count'
  | 'alive'
  | 'centers'
  | 'scales'
  | 'rotations'
  | 'opacities'
  | 'colors'
  | 'shDegree'
  | 'shRest'
>;
export interface ExportLayer {
  store: ExportStore;
  matrix: readonly number[];
  visible?: boolean;
}
export interface PlyWriteOptions {
  includeHidden?: boolean;
  includeSh?: boolean;
  version?: string;
}

interface Transform {
  elements: readonly number[];
  scale: number;
  rotation: [number, number, number, number];
}

function layerTransform(elements: readonly number[]): Transform {
  if (elements.length !== 16) throw new Error('Layer export matrix must have 16 elements');
  const sx = Math.hypot(elements[0] ?? 1, elements[1] ?? 0, elements[2] ?? 0) || 1;
  const sy = Math.hypot(elements[4] ?? 0, elements[5] ?? 1, elements[6] ?? 0) || 1;
  const sz = Math.hypot(elements[8] ?? 0, elements[9] ?? 0, elements[10] ?? 1) || 1;
  const m00 = (elements[0] ?? 1) / sx,
    m01 = (elements[4] ?? 0) / sy,
    m02 = (elements[8] ?? 0) / sz;
  const m10 = (elements[1] ?? 0) / sx,
    m11 = (elements[5] ?? 1) / sy,
    m12 = (elements[9] ?? 0) / sz;
  const m20 = (elements[2] ?? 0) / sx,
    m21 = (elements[6] ?? 0) / sy,
    m22 = (elements[10] ?? 1) / sz;
  const trace = m00 + m11 + m22;
  let x: number, y: number, z: number, w: number;
  if (trace > 0) {
    const s = 2 * Math.sqrt(trace + 1);
    w = 0.25 * s;
    x = (m21 - m12) / s;
    y = (m02 - m20) / s;
    z = (m10 - m01) / s;
  } else if (m00 > m11 && m00 > m22) {
    const s = 2 * Math.sqrt(1 + m00 - m11 - m22);
    w = (m21 - m12) / s;
    x = 0.25 * s;
    y = (m01 + m10) / s;
    z = (m02 + m20) / s;
  } else if (m11 > m22) {
    const s = 2 * Math.sqrt(1 + m11 - m00 - m22);
    w = (m02 - m20) / s;
    x = (m01 + m10) / s;
    y = 0.25 * s;
    z = (m12 + m21) / s;
  } else {
    const s = 2 * Math.sqrt(1 + m22 - m00 - m11);
    w = (m10 - m01) / s;
    x = (m02 + m20) / s;
    y = (m12 + m21) / s;
    z = 0.25 * s;
  }
  const length = Math.hypot(x, y, z, w) || 1;
  return {
    elements,
    scale: (sx + sy + sz) / 3,
    rotation: [x / length, y / length, z / length, w / length],
  };
}

function multiplyQuat(
  a: readonly number[] | Float32Array,
  b: readonly number[] | Float32Array,
): [number, number, number, number] {
  const [ax = 0, ay = 0, az = 0, aw = 1] = a;
  const [bx = 0, by = 0, bz = 0, bw = 1] = b;
  const q: [number, number, number, number] = [
    aw * bx + ax * bw + ay * bz - az * by,
    aw * by - ax * bz + ay * bw + az * bx,
    aw * bz + ax * by - ay * bx + az * bw,
    aw * bw - ax * bx - ay * by - az * bz,
  ];
  const length = Math.hypot(...q) || 1;
  return q.map((value) => value / length) as [number, number, number, number];
}

export function gaussianPlyHeader(count: number, degree: ShDegree, version = '0.1.0'): string {
  const lines = [
    'ply',
    'format binary_little_endian 1.0',
    `comment Generated by Splatypus ${version}`,
    `element vertex ${count}`,
    'property float x',
    'property float y',
    'property float z',
    'property float nx',
    'property float ny',
    'property float nz',
    'property float f_dc_0',
    'property float f_dc_1',
    'property float f_dc_2',
  ];
  for (let index = 0; index < shCoefficients(degree); index += 1)
    lines.push(`property float f_rest_${index}`);
  lines.push(
    'property float opacity',
    'property float scale_0',
    'property float scale_1',
    'property float scale_2',
    'property float rot_0',
    'property float rot_1',
    'property float rot_2',
    'property float rot_3',
    'end_header',
    '',
  );
  return lines.join('\n');
}

function selected(layers: ExportLayer[], options: PlyWriteOptions): ExportLayer[] {
  return layers.filter((layer) => (options.includeHidden ?? false) || layer.visible !== false);
}

function liveCount(store: ExportStore): number {
  let count = 0;
  for (const alive of store.alive) count += alive;
  return count;
}

export function estimateGaussianPlyBytes(
  layers: ExportLayer[],
  options: PlyWriteOptions = {},
): number {
  const exported = selected(layers, options);
  const count = exported.reduce((sum, layer) => sum + liveCount(layer.store), 0);
  const degree =
    options.includeSh === false
      ? 0
      : (Math.max(0, ...exported.map((layer) => layer.store.shDegree)) as ShDegree);
  return (
    new TextEncoder().encode(gaussianPlyHeader(count, degree, options.version)).byteLength +
    count * (17 + shCoefficients(degree)) * 4
  );
}

export function writeGaussianPly(
  layers: ExportLayer[],
  options: PlyWriteOptions = {},
  onProgress?: (written: number, total: number) => void,
): ArrayBuffer {
  const exported = selected(layers, options);
  const total = exported.reduce((sum, layer) => sum + liveCount(layer.store), 0);
  const degree =
    options.includeSh === false
      ? 0
      : (Math.max(0, ...exported.map((layer) => layer.store.shDegree)) as ShDegree);
  const coeffs = shCoefficients(degree);
  const headerBytes = new TextEncoder().encode(gaussianPlyHeader(total, degree, options.version));
  const output = new ArrayBuffer(headerBytes.byteLength + total * (17 + coeffs) * 4);
  new Uint8Array(output, 0, headerBytes.byteLength).set(headerBytes);
  const view = new DataView(output);
  let offset = headerBytes.byteLength;
  let written = 0;
  let reportedAt = performance.now();
  const put = (value: number): void => {
    view.setFloat32(offset, value, true);
    offset += 4;
  };
  for (const layer of exported) {
    const transform = layerTransform(layer.matrix);
    const e = transform.elements;
    const sourceCoeffs = shCoefficients(layer.store.shDegree);
    const sourcePerChannel = sourceCoeffs / 3;
    const targetPerChannel = coeffs / 3;
    for (let index = 0; index < layer.store.count; index += 1) {
      if (!layer.store.alive[index]) continue;
      const i3 = index * 3,
        i4 = index * 4;
      const x = layer.store.centers[i3] ?? 0,
        y = layer.store.centers[i3 + 1] ?? 0,
        z = layer.store.centers[i3 + 2] ?? 0;
      put((e[0] ?? 1) * x + (e[4] ?? 0) * y + (e[8] ?? 0) * z + (e[12] ?? 0));
      put((e[1] ?? 0) * x + (e[5] ?? 1) * y + (e[9] ?? 0) * z + (e[13] ?? 0));
      put((e[2] ?? 0) * x + (e[6] ?? 0) * y + (e[10] ?? 1) * z + (e[14] ?? 0));
      put(0);
      put(0);
      put(0);
      put(((layer.store.colors[i3] ?? 0.5) - 0.5) / SH_C0);
      put(((layer.store.colors[i3 + 1] ?? 0.5) - 0.5) / SH_C0);
      put(((layer.store.colors[i3 + 2] ?? 0.5) - 0.5) / SH_C0);
      for (let channel = 0; channel < 3; channel += 1)
        for (let coefficient = 0; coefficient < targetPerChannel; coefficient += 1)
          put(
            coefficient < sourcePerChannel && layer.store.shRest
              ? (layer.store.shRest[
                  index * sourceCoeffs + channel * sourcePerChannel + coefficient
                ] ?? 0)
              : 0,
          );
      const opacity = Math.min(1 - 1e-6, Math.max(1e-6, layer.store.opacities[index] ?? 1));
      put(Math.log(opacity / (1 - opacity)));
      put(Math.log(Math.max((layer.store.scales[i3] ?? 1) * transform.scale, 1e-9)));
      put(Math.log(Math.max((layer.store.scales[i3 + 1] ?? 1) * transform.scale, 1e-9)));
      put(Math.log(Math.max((layer.store.scales[i3 + 2] ?? 1) * transform.scale, 1e-9)));
      const rotation = multiplyQuat(transform.rotation, layer.store.rotations.subarray(i4, i4 + 4));
      put(rotation[3]);
      put(rotation[0]);
      put(rotation[1]);
      put(rotation[2]);
      written += 1;
      if (onProgress && (written === total || performance.now() - reportedAt >= 250)) {
        onProgress(written, total);
        reportedAt = performance.now();
      }
    }
  }
  return output;
}
